# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strm < Formula
  desc "Command Line Interface for https://streammachine.io"
  homepage "https://streammachine.io"
  version "1.3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streammachineio/cli/releases/download/v1.3.0/strm_darwin_amd64.tar.gz"
      sha256 "2f4516f391c59610e9702bb9ecea81d89ebcbedff176142ee518037ef1018a3b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/streammachineio/cli/releases/download/v1.3.0/strm_darwin_arm64.tar.gz"
      sha256 "98cc96ec2dbf283f34adee6505900cb660b8171c04e3d896fb249d63d70ee918"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streammachineio/cli/releases/download/v1.3.0/strm_linux_amd64.tar.gz"
      sha256 "bb42e9dad0e58ca83b62368f15cbf80322ae53b9f0563f05ce86ea132ddb62f2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streammachineio/cli/releases/download/v1.3.0/strm_linux_arm64.tar.gz"
      sha256 "4a176902af21e4554c9fe2d6f779715fc449b6ebf7b9eacc7e1c27381894a86d"
    end
  end

  def install
    bin.install "strm"
  end

  def caveats; <<~EOS
    In order to set up auto completion, please follow the instructions below. When you've set up auto completion in the past, you can skip these instructions.

     for bash users
       add the following line to your .bash_profile or .bashrc:
         source <(strm completion bash)

       to load completions for each session, execute once:
         - Linux users: strm completion bash > /etc/bash_completion.d/strm
         - macOS users: strm completion bash > /usr/local/etc/bash_completion.d/strm

     for zsh users
       ensure that shell completion is enabled, then run (only needs to be done once):
         /bin/zsh -c 'strm completion zsh > "${fpath[1]}/_strm"'

     for fish users
       source "strm/path.fish.inc"
  EOS
  end

  test do
    system "#{bin}/strm --version"
  end
end
