# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strm < Formula
  desc "Command Line Interface for https://strmprivacy.io"
  homepage "https://strmprivacy.io"
  version "3.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/strmprivacy/cli/releases/download/v3.12.0/strm_darwin_amd64.tar.gz"
      sha256 "74ccbdb681e3c3eb4d8c3d9caa9122d19b06eb7c8a3cd0b1e5f64187be5a630a"

      def install
        bin.install "strm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/strmprivacy/cli/releases/download/v3.12.0/strm_darwin_arm64.tar.gz"
      sha256 "f887e434006600ea2d3abc0d8e9d79160cc60f5a96301d8e5256b39b20553fa3"

      def install
        bin.install "strm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/strmprivacy/cli/releases/download/v3.12.0/strm_linux_amd64.tar.gz"
      sha256 "eed6a4e76015a1fabdf52cef4abd27ff571e35abb13ffd437955265026a154bc"

      def install
        bin.install "strm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/strmprivacy/cli/releases/download/v3.12.0/strm_linux_arm64.tar.gz"
      sha256 "976da2eb1a4245a332f549f6bbd082be7ad4f934e0fe603a3091365390925f04"

      def install
        bin.install "strm"
      end
    end
  end

  def caveats
    <<~EOS
      In order to set up auto completion, please follow the instructions below. When you've set up auto completion in the past, you can skip these instructions.

       for bash users
         add the following line to your .bash_profile or .bashrc:
           source <(strm completion bash)

         to load completions for each session, execute once:
           - Linux users: strm completion bash > /etc/bash_completion.d/strm
           - macOS users: strm completion bash > /usr/local/etc/bash_completion.d/strm

       for zsh users
         ensure that shell completion is enabled, then run (only needs to be done once):
           strm completion zsh > "${fpath[1]}/_strm"

       for fish users
         strm completion fish > ~/.config/fish/completions/strm.fish # or $XDG_CONFIG_HOME instead of ~/.config
    EOS
  end

  test do
    system "#{bin}/strm --version"
  end
end
